### ISSUE TITLE
Show and hide user gist

### ISSUE THREAD

**Issue by enderahmetyurt** [enderahmetyurt/gistcatch#4]
On user gist page show and hide gist by clicking gist link

**Comment by enderahmetyurt** [comment]
Yes. You can do it with your assumption. I want to show an example of what I really want. https://getbootstrap.com/docs/4.0/components/collapse/ When the user clicks the gist name on the list and open a div which includes gist codes and then click again the link div should be close.

**Comment by shivanibhanwal** [comment]
@enderahmetyurt 👍 we thought same thing I planned it this way https://getbootstrap.com/docs/4.0/components/list-group/#javascript-behavior

**Comment by enderahmetyurt** [comment]
No. I guess we should do toggle below the gist link. Because opening it left of the link cannot be fit in a div or it should be smaller. Can you do it as I mentioned?

**Comment by shivanibhanwal** [comment]
On I forgot to mention I am taking the approach of list_group but I am doing it below the List item, not on right @enderahmetyurt 
which is same as your example difference is I am not using accordion

**Comment by shivanibhanwal** [comment]
@enderahmetyurt I have completed implementation of show/hide. Attached is the screenshot. Only thing which I have some issue is with the Content displaying as it comes in `gist editor` because every file is of different format e.g .rb, .md 
I tried Redcarpet Markdown and Rouge syntax highlighter, but markdown changes it to HTML which is not case with all the gist. I explored Rouge but need to see if we can do that based on just file extension with Rouge. But for now I am committing changes. Let me know your thought
<img width="937" alt="screen shot 2018-10-17 at 9 21 07 pm" src="https://user-images.githubusercontent.com/1167588/47099555-29c9a700-d253-11e8-90e4-da4f5248dfd8.png">

**Comment by enderahmetyurt** [comment]
Thank you @shivanibhanwal but it's not working properly.
<img width="960" alt="screen shot 2018-10-17 at 22 52 27" src="https://user-images.githubusercontent.com/447588/47112553-5a174280-d25f-11e8-854d-6ac5651d3330.png">

 I want to make some color with Redcarpet. Gist API gives the extension of the gist. It doesn't make any sense with raw html.

**Comment by shivanibhanwal** [comment]
@enderahmetyurt Markdown redcarpet will not help with syntax highlitghter only that case be changed. I need to explore that more.

**Comment by enderahmetyurt** [comment]
Okay. Could you fix the accordion problem?

**Comment by enderahmetyurt** [comment]
Great. It looks nice @shivanibhanwal I will be check later. Thanks 🙏
